const APP_CONSTANTS = {
  done: 'Xong',
  alarm: 'Báo thức',
  timer: 'Đếm ngược',
  stopWatch: 'Bấm giờ',
  setting: 'Cài đặt',
  alarmSound: 'Âm thanh báo thức',
  vibration: 'Rung',
  sleepMode: 'Chế độ ngủ',
  labelAlarm: 'Nhãn báo thức',
  repeat: 'Lặp lại',
  snooze: 'Nhắc lại',
  ringtone: 'Nhạc chuông',
  volume: 'Âm lượng',
  deleteAfterDismissed: 'Xóa sau khi tắt báo thức',
  volumesAndSounds: 'Âm lượng và âm thanh',
  volumeAlarm: 'Âm lượng báo thức',
  gentlePreAlarm: 'Báo thức trước nhẹ nhàng',
  durations: 'Thời gian',
  skipAlarmNotification: 'Bỏ qua thông báo báo thức',
  preAlarmDuration: 'Thời gian báo thức trước',
  fadeInDuration: 'Thời gian hiển thị',
  againDuration: 'Thời gian nhắc lại',
  autoSilent: 'Tự động im lặng',
  cancel: 'Hủy',
  save: 'Lưu',
  minutes: 'Phút',
  hours: 'Giờ',
  days: 'Ngày',
  seconds: 'Giây',
  off: 'Tắt',
  on: 'Bật',
  never: 'Không bao giờ',
  everyDay: 'Mỗi ngày',
  fromMondayToFriday: 'Từ thứ 2 đến thứ 6',
  custom: 'Tùy chỉnh',
  oneTime: 'Một lần',
  monday: 'Thứ 2',
  tuesday: 'Thứ 3',
  wednesday: 'Thứ 4',
  thursday: 'Thứ 5',
  friday: 'Thứ 6',
  saturday: 'Thứ 7',
  sunday: 'Chủ nhật',
  ok: 'Đồng ý',
  thereIsNoAlarm: 'Không có báo thức nào',
};

export {APP_CONSTANTS};
